-- HVAC Plan Studio Cloud Projects and Collaboration foundation.
-- Supabase Auth owns account identities. RLS protects every project record.

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null default '',
  source_file_name text,
  source_drive_file_id text,
  drive_package_file_id text,
  drive_package_url text,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.project_members (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  invited_email text,
  role text not null default 'viewer' check (role in ('owner', 'editor', 'viewer')),
  status text not null default 'pending' check (status in ('pending', 'active')),
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  check (user_id is not null or invited_email is not null)
);

create table public.project_revisions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  revision_number bigint not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Drawing revision',
  summary text not null default '',
  snapshot jsonb not null,
  drawing_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique(project_id, revision_number)
);

create table public.project_activity (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index project_members_user_unique
  on public.project_members(project_id, user_id)
  where user_id is not null;
create unique index project_members_invite_unique
  on public.project_members(project_id, lower(invited_email))
  where invited_email is not null and status = 'pending';
create index projects_owner_updated_idx on public.projects(owner_id, updated_at desc);
create index project_members_user_idx on public.project_members(user_id, status);
create index project_members_invited_by_idx on public.project_members(invited_by);
create index project_revisions_project_idx on public.project_revisions(project_id, revision_number desc);
create index project_revisions_created_by_idx on public.project_revisions(created_by);
create index project_activity_project_idx on public.project_activity(project_id, created_at desc);
create index project_activity_actor_idx on public.project_activity(actor_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, email, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(
      new.raw_user_meta_data ->> 'display_name',
      new.raw_user_meta_data ->> 'full_name',
      split_part(coalesce(new.email, ''), '@', 1)
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = coalesce(public.profiles.display_name, excluded.display_name);
  return new;
end;
$$;

create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_user();

create or replace function public.add_project_owner_member()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.project_members(
    project_id,
    user_id,
    role,
    status,
    invited_by,
    accepted_at
  )
  values (new.id, new.owner_id, 'owner', 'active', new.owner_id, now())
  on conflict do nothing;

  insert into public.project_activity(project_id, actor_id, action, details)
  values (
    new.id,
    new.owner_id,
    'project_created',
    jsonb_build_object('name', new.name)
  );
  return new;
end;
$$;

create trigger on_project_created
after insert on public.projects
for each row execute function public.add_project_owner_member();

create or replace function private.is_project_member(project_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.projects p
    where p.id = project_uuid
      and p.owner_id = auth.uid()
  ) or exists (
    select 1
    from public.project_members pm
    where pm.project_id = project_uuid
      and pm.user_id = auth.uid()
      and pm.status = 'active'
  );
$$;

create or replace function private.can_edit_project(project_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.projects p
    where p.id = project_uuid
      and p.owner_id = auth.uid()
  ) or exists (
    select 1
    from public.project_members pm
    where pm.project_id = project_uuid
      and pm.user_id = auth.uid()
      and pm.status = 'active'
      and pm.role in ('owner', 'editor')
  );
$$;

create or replace function public.claim_project_invitations()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed integer;
  account_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if auth.uid() is null or account_email = '' then
    return 0;
  end if;

  update public.project_members
  set user_id = auth.uid(),
      status = 'active',
      accepted_at = now()
  where user_id is null
    and status = 'pending'
    and lower(invited_email) = account_email;

  get diagnostics claimed = row_count;
  return claimed;
end;
$$;

create or replace function public.log_revision_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.projects
  set updated_at = now()
  where id = new.project_id;

  insert into public.project_activity(project_id, actor_id, action, details)
  values (
    new.project_id,
    new.created_by,
    'revision_saved',
    jsonb_build_object(
      'revision', new.revision_number,
      'title', new.title,
      'drawing_count', new.drawing_count
    )
  );
  return new;
end;
$$;

create trigger on_revision_created
after insert on public.project_revisions
for each row execute function public.log_revision_activity();

create or replace function public.save_project_revision(
  project_uuid uuid,
  revision_title text,
  revision_summary text,
  revision_snapshot jsonb,
  revision_drawing_count integer
)
returns public.project_revisions
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  next_revision bigint;
  created_revision public.project_revisions;
begin
  if auth.uid() is null or not private.can_edit_project(project_uuid) then
    raise exception 'You do not have permission to save this project';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(project_uuid::text, 0));
  select coalesce(max(revision_number), 0) + 1
  into next_revision
  from public.project_revisions
  where project_id = project_uuid;

  insert into public.project_revisions(
    project_id,
    revision_number,
    created_by,
    title,
    summary,
    snapshot,
    drawing_count
  )
  values (
    project_uuid,
    next_revision,
    auth.uid(),
    coalesce(nullif(trim(revision_title), ''), 'Revision ' || next_revision),
    coalesce(trim(revision_summary), ''),
    revision_snapshot,
    greatest(coalesce(revision_drawing_count, 0), 0)
  )
  returning * into created_revision;

  return created_revision;
end;
$$;

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.project_revisions enable row level security;
alter table public.project_activity enable row level security;

create policy profiles_select_own
on public.profiles for select to authenticated
using (id = (select auth.uid()));
create policy profiles_insert_own
on public.profiles for insert to authenticated
with check (id = (select auth.uid()));
create policy profiles_update_own
on public.profiles for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy projects_select_member
on public.projects for select to authenticated
using (private.is_project_member(id));
create policy projects_insert_owner
on public.projects for insert to authenticated
with check (owner_id = (select auth.uid()));
create policy projects_update_editor
on public.projects for update to authenticated
using (private.can_edit_project(id))
with check (private.can_edit_project(id));
create policy projects_delete_owner
on public.projects for delete to authenticated
using (owner_id = (select auth.uid()));

create policy members_select_member
on public.project_members for select to authenticated
using (
  private.is_project_member(project_id)
  or user_id = (select auth.uid())
  or (
    status = 'pending'
    and lower(invited_email) =
      lower(coalesce((select auth.jwt()) ->> 'email', ''))
  )
);
create policy members_insert_owner
on public.project_members for insert to authenticated
with check (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_id = (select auth.uid())
  )
);
create policy members_update_owner
on public.project_members for update to authenticated
using (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_id = (select auth.uid())
  )
);
create policy members_delete_owner
on public.project_members for delete to authenticated
using (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_id = (select auth.uid())
  )
  and role <> 'owner'
);

create policy revisions_select_member
on public.project_revisions for select to authenticated
using (private.is_project_member(project_id));
create policy revisions_insert_editor
on public.project_revisions for insert to authenticated
with check (
  private.can_edit_project(project_id)
  and created_by = (select auth.uid())
);

create policy activity_select_member
on public.project_activity for select to authenticated
using (private.is_project_member(project_id));
create policy activity_insert_editor
on public.project_activity for insert to authenticated
with check (
  private.can_edit_project(project_id)
  and actor_id = (select auth.uid())
);

grant usage on schema public to authenticated;
grant select, insert, update, delete
  on public.profiles, public.projects, public.project_members
  to authenticated;
grant select, insert
  on public.project_revisions, public.project_activity
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function private.is_project_member(uuid) to authenticated;
grant execute on function private.can_edit_project(uuid) to authenticated;
grant execute on function public.claim_project_invitations() to authenticated;
grant execute on function public.save_project_revision(
  uuid,
  text,
  text,
  jsonb,
  integer
) to authenticated;

revoke execute on function public.set_updated_at()
  from public, anon, authenticated;
revoke execute on function public.handle_new_user()
  from public, anon, authenticated;
revoke execute on function public.add_project_owner_member()
  from public, anon, authenticated;
revoke execute on function public.log_revision_activity()
  from public, anon, authenticated;
revoke execute on function public.claim_project_invitations()
  from public, anon;
revoke execute on function public.save_project_revision(
  uuid,
  text,
  text,
  jsonb,
  integer
) from public, anon;
