-- HVAC Plan Studio v100 — Project Intelligence Hub.
-- Adds project-scoped coordination, approvals, and file evidence while keeping
-- drawing geometry exclusively inside immutable named revisions.

begin;

alter table public.project_revisions
  add column if not exists workflow_summary jsonb not null default '{}'::jsonb,
  add column if not exists content_hash text;

update public.project_revisions
set workflow_summary = coalesce(snapshot -> 'workflowSummary', '{}'::jsonb),
    content_hash = encode(extensions.digest(snapshot::text, 'sha256'), 'hex')
where content_hash is null;

alter table public.project_revisions
  alter column content_hash set not null;

create unique index if not exists project_revisions_project_id_id_idx
  on public.project_revisions(project_id, id);

create table if not exists public.project_work_items (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  revision_id uuid,
  kind text not null check (kind in ('issue', 'task')),
  status text not null default 'open'
    check (status in ('open', 'in_progress', 'blocked', 'resolved', 'closed')),
  priority text not null default 'medium'
    check (priority in ('critical', 'high', 'medium', 'low')),
  category text not null default 'coordination',
  title text not null check (char_length(trim(title)) between 1 and 160),
  description text not null default '',
  system_id text,
  page_number integer check (page_number is null or page_number > 0),
  drawing_id text,
  anchor jsonb not null default '{}'::jsonb
    check (jsonb_typeof(anchor) = 'object'),
  assigned_to uuid references auth.users(id) on delete set null,
  due_at timestamptz,
  created_by uuid not null references auth.users(id) on delete restrict,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, id),
  foreign key(project_id, revision_id)
    references public.project_revisions(project_id, id)
    on delete set null (revision_id)
);

create table if not exists public.project_comments (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  work_item_id uuid not null,
  author_id uuid not null references auth.users(id) on delete restrict,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  foreign key(project_id, work_item_id)
    references public.project_work_items(project_id, id)
    on delete cascade
);

create table if not exists public.project_approvals (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  revision_id uuid not null,
  reviewer_id uuid not null references auth.users(id) on delete restrict,
  requested_by uuid not null references auth.users(id) on delete restrict,
  status text not null default 'requested'
    check (status in ('requested', 'approved', 'changes_requested')),
  decision_note text not null default '',
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  unique(revision_id, reviewer_id),
  foreign key(project_id, revision_id)
    references public.project_revisions(project_id, id)
    on delete cascade
);

create table if not exists public.project_files (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  revision_id uuid,
  kind text not null
    check (kind in (
      'source_plan',
      'cloud_package',
      'field_release',
      'takeoff',
      'submittal',
      'photo',
      'other'
    )),
  provider text not null default 'google_drive'
    check (provider = 'google_drive'),
  provider_file_id text not null,
  display_name text not null,
  mime_type text,
  web_view_url text,
  status text not null default 'active'
    check (status in ('active', 'archived')),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, provider, provider_file_id),
  foreign key(project_id, revision_id)
    references public.project_revisions(project_id, id)
    on delete set null (revision_id)
);

create index if not exists project_work_items_attention_idx
  on public.project_work_items(project_id, status, priority, updated_at desc);
create index if not exists project_work_items_assignee_idx
  on public.project_work_items(assigned_to, status, due_at);
create index if not exists project_comments_item_idx
  on public.project_comments(work_item_id, created_at);
create index if not exists project_approvals_revision_idx
  on public.project_approvals(project_id, revision_id, status);
create index if not exists project_files_project_idx
  on public.project_files(project_id, kind, updated_at desc);

drop trigger if exists project_files_set_updated_at on public.project_files;
create trigger project_files_set_updated_at
before update on public.project_files
for each row execute function public.set_updated_at();

create or replace function public.prepare_project_work_item()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  if tg_op = 'UPDATE' then
    new.version = old.version + 1;
  end if;
  if new.status in ('resolved', 'closed') and old.status not in ('resolved', 'closed') then
    new.resolved_by = auth.uid();
    new.resolved_at = now();
  elsif new.status not in ('resolved', 'closed') then
    new.resolved_by = null;
    new.resolved_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists project_work_items_prepare on public.project_work_items;
create trigger project_work_items_prepare
before update on public.project_work_items
for each row execute function public.prepare_project_work_item();

create or replace function public.prepare_project_approval()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if old.status <> 'requested' then
    raise exception 'Approval decisions are final';
  end if;
  if new.status = 'requested' then
    raise exception 'Choose approved or changes requested';
  end if;
  if new.status = 'changes_requested' and nullif(trim(new.decision_note), '') is null then
    raise exception 'A note is required when requesting changes';
  end if;
  new.decided_at = now();
  return new;
end;
$$;

drop trigger if exists project_approvals_prepare on public.project_approvals;
create trigger project_approvals_prepare
before update on public.project_approvals
for each row execute function public.prepare_project_approval();

create or replace function public.log_project_intelligence_activity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  activity_action text;
  activity_project uuid;
  activity_details jsonb;
begin
  activity_project := new.project_id;
  if tg_table_name = 'project_work_items' then
    activity_action := case when tg_op = 'INSERT' then 'work_item_created' else 'work_item_updated' end;
    activity_details := jsonb_build_object(
      'work_item_id', new.id,
      'kind', new.kind,
      'status', new.status,
      'priority', new.priority,
      'title', new.title
    );
  elsif tg_table_name = 'project_comments' then
    activity_action := 'work_item_commented';
    activity_details := jsonb_build_object('work_item_id', new.work_item_id);
  elsif tg_table_name = 'project_approvals' then
    activity_action := case when tg_op = 'INSERT' then 'approval_requested' else 'approval_decided' end;
    activity_details := jsonb_build_object(
      'approval_id', new.id,
      'revision_id', new.revision_id,
      'status', new.status
    );
  else
    activity_action := case when tg_op = 'INSERT' then 'project_file_registered' else 'project_file_updated' end;
    activity_details := jsonb_build_object(
      'file_id', new.id,
      'kind', new.kind,
      'display_name', new.display_name
    );
  end if;

  insert into public.project_activity(project_id, actor_id, action, details)
  values (activity_project, auth.uid(), activity_action, activity_details);

  update public.projects set updated_at = now() where id = activity_project;
  return new;
end;
$$;

drop trigger if exists project_work_items_activity on public.project_work_items;
create trigger project_work_items_activity
after insert or update on public.project_work_items
for each row execute function public.log_project_intelligence_activity();

drop trigger if exists project_comments_activity on public.project_comments;
create trigger project_comments_activity
after insert on public.project_comments
for each row execute function public.log_project_intelligence_activity();

drop trigger if exists project_approvals_activity on public.project_approvals;
create trigger project_approvals_activity
after insert or update on public.project_approvals
for each row execute function public.log_project_intelligence_activity();

drop trigger if exists project_files_activity on public.project_files;
create trigger project_files_activity
after insert or update on public.project_files
for each row execute function public.log_project_intelligence_activity();

alter table public.project_work_items enable row level security;
alter table public.project_comments enable row level security;
alter table public.project_approvals enable row level security;
alter table public.project_files enable row level security;

drop policy if exists work_items_select_member on public.project_work_items;
create policy work_items_select_member
on public.project_work_items for select to authenticated
using (private.is_project_member(project_id));

drop policy if exists work_items_insert_editor on public.project_work_items;
create policy work_items_insert_editor
on public.project_work_items for insert to authenticated
with check (
  private.can_edit_project(project_id)
  and created_by = (select auth.uid())
  and status = 'open'
  and resolved_by is null
  and resolved_at is null
  and version = 1
  and (
    assigned_to is null
    or exists (
      select 1
      from public.project_members assignee
      where assignee.project_id = project_work_items.project_id
        and assignee.user_id = project_work_items.assigned_to
        and assignee.status = 'active'
    )
  )
);

drop policy if exists work_items_update_editor on public.project_work_items;
create policy work_items_update_editor
on public.project_work_items for update to authenticated
using (private.can_edit_project(project_id))
with check (private.can_edit_project(project_id));

drop policy if exists comments_select_member on public.project_comments;
create policy comments_select_member
on public.project_comments for select to authenticated
using (private.is_project_member(project_id));

drop policy if exists comments_insert_editor on public.project_comments;
create policy comments_insert_editor
on public.project_comments for insert to authenticated
with check (
  private.is_project_member(project_id)
  and author_id = (select auth.uid())
);

drop policy if exists approvals_select_member on public.project_approvals;
create policy approvals_select_member
on public.project_approvals for select to authenticated
using (private.is_project_member(project_id));

drop policy if exists approvals_request_editor on public.project_approvals;
create policy approvals_request_editor
on public.project_approvals for insert to authenticated
with check (
  private.can_edit_project(project_id)
  and requested_by = (select auth.uid())
  and status = 'requested'
  and decided_at is null
  and exists (
    select 1
    from public.project_members reviewer
    where reviewer.project_id = project_approvals.project_id
      and reviewer.user_id = project_approvals.reviewer_id
      and reviewer.status = 'active'
  )
);

drop policy if exists approvals_decide_reviewer on public.project_approvals;
create policy approvals_decide_reviewer
on public.project_approvals for update to authenticated
using (reviewer_id = (select auth.uid()))
with check (reviewer_id = (select auth.uid()));

drop policy if exists files_select_member on public.project_files;
create policy files_select_member
on public.project_files for select to authenticated
using (private.is_project_member(project_id));

drop policy if exists files_insert_editor on public.project_files;
create policy files_insert_editor
on public.project_files for insert to authenticated
with check (
  private.can_edit_project(project_id)
  and created_by = (select auth.uid())
);

drop policy if exists files_update_editor on public.project_files;
create policy files_update_editor
on public.project_files for update to authenticated
using (private.can_edit_project(project_id))
with check (private.can_edit_project(project_id));

grant select on
  public.project_work_items,
  public.project_comments,
  public.project_approvals,
  public.project_files
to authenticated;

revoke insert on
  public.project_work_items,
  public.project_comments,
  public.project_approvals,
  public.project_files
from authenticated;

grant insert (
  project_id,
  revision_id,
  kind,
  priority,
  category,
  title,
  description,
  system_id,
  page_number,
  drawing_id,
  anchor,
  assigned_to,
  due_at,
  created_by
) on public.project_work_items to authenticated;

grant insert (
  project_id,
  work_item_id,
  author_id,
  body
) on public.project_comments to authenticated;

grant insert (
  project_id,
  revision_id,
  reviewer_id,
  requested_by,
  status
) on public.project_approvals to authenticated;

grant insert (
  project_id,
  revision_id,
  kind,
  provider,
  provider_file_id,
  display_name,
  mime_type,
  web_view_url,
  created_by
) on public.project_files to authenticated;

grant update (
  kind,
  status,
  priority,
  category,
  title,
  description,
  system_id,
  page_number,
  drawing_id,
  anchor,
  assigned_to,
  due_at
) on public.project_work_items to authenticated;

grant update (
  status,
  decision_note
) on public.project_approvals to authenticated;

grant update (
  revision_id,
  kind,
  display_name,
  mime_type,
  web_view_url,
  status
) on public.project_files to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- Prevent direct mutation of ownership, verified Drive state, immutable revisions,
-- and trustworthy activity history.
revoke update on public.projects from authenticated;
grant update (
  name,
  description,
  source_file_name,
  source_drive_file_id
) on public.projects to authenticated;

revoke insert on public.project_revisions from authenticated;
revoke insert on public.project_activity from authenticated;
drop policy if exists activity_insert_editor on public.project_activity;

create or replace function public.save_project_revision(
  project_uuid uuid,
  revision_title text,
  revision_summary text,
  revision_snapshot jsonb,
  revision_drawing_count integer
)
returns public.project_revisions
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  next_revision bigint;
  created_revision public.project_revisions;
  next_workflow_summary jsonb;
begin
  if auth.uid() is null or not private.can_edit_project(project_uuid) then
    raise exception 'You do not have permission to save this project';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(project_uuid::text, 0));
  select coalesce(max(revision_number), 0) + 1
  into next_revision
  from public.project_revisions
  where project_id = project_uuid;

  next_workflow_summary := coalesce(revision_snapshot -> 'workflowSummary', '{}'::jsonb);

  insert into public.project_revisions(
    project_id,
    revision_number,
    created_by,
    title,
    summary,
    snapshot,
    drawing_count,
    workflow_summary,
    content_hash
  )
  values (
    project_uuid,
    next_revision,
    auth.uid(),
    coalesce(nullif(trim(revision_title), ''), 'Revision ' || next_revision),
    coalesce(trim(revision_summary), ''),
    revision_snapshot,
    greatest(coalesce(revision_drawing_count, 0), 0),
    next_workflow_summary,
    encode(extensions.digest(revision_snapshot::text, 'sha256'), 'hex')
  )
  returning * into created_revision;

  update public.projects
  set workflow_summary = next_workflow_summary,
      updated_at = now()
  where id = project_uuid;

  return created_revision;
end;
$$;

create or replace function public.record_drive_package_sync(
  project_uuid uuid,
  package_file_id text,
  package_file_url text,
  synced_revision bigint
)
returns public.projects
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  updated_project public.projects;
  synced_revision_id uuid;
  package_name text;
begin
  if auth.uid() is null or not private.can_edit_project(project_uuid) then
    raise exception 'You do not have permission to sync this project';
  end if;

  if nullif(trim(package_file_id), '') is null or synced_revision < 1 then
    raise exception 'A valid Drive file and cloud revision are required';
  end if;

  select id
  into synced_revision_id
  from public.project_revisions
  where project_id = project_uuid
    and revision_number = synced_revision;

  if synced_revision_id is null then
    raise exception 'The selected cloud revision does not exist';
  end if;

  update public.projects
  set drive_package_file_id = package_file_id,
      drive_package_url = nullif(trim(package_file_url), ''),
      drive_synced_revision_number = synced_revision,
      drive_synced_at = now()
  where id = project_uuid
  returning * into updated_project;

  if updated_project.id is null then
    raise exception 'Project not found';
  end if;
  package_name := coalesce(nullif(trim(updated_project.name), ''), 'HVAC Plan Studio') || '.hvacplan.json';

  insert into public.project_files(
    project_id,
    revision_id,
    kind,
    provider,
    provider_file_id,
    display_name,
    mime_type,
    web_view_url,
    status,
    created_by
  )
  values (
    project_uuid,
    synced_revision_id,
    'cloud_package',
    'google_drive',
    package_file_id,
    package_name,
    'application/json',
    nullif(trim(package_file_url), ''),
    'active',
    auth.uid()
  )
  on conflict (project_id, provider, provider_file_id)
  do update set
    revision_id = excluded.revision_id,
    display_name = excluded.display_name,
    mime_type = excluded.mime_type,
    web_view_url = excluded.web_view_url,
    status = 'active';

  insert into public.project_activity(project_id, actor_id, action, details)
  values (
    project_uuid,
    auth.uid(),
    'drive_package_synced',
    jsonb_build_object(
      'revision', synced_revision,
      'drive_file_id', package_file_id
    )
  );

  return updated_project;
end;
$$;

create or replace function public.set_project_status(
  project_uuid uuid,
  next_status text
)
returns public.projects
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  updated_project public.projects;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if next_status not in ('active', 'archived') then
    raise exception 'Invalid project status';
  end if;
  if not exists (
    select 1 from public.projects
    where id = project_uuid and owner_id = auth.uid()
  ) then
    raise exception 'Only the project owner can change project status';
  end if;

  update public.projects
  set status = next_status
  where id = project_uuid
  returning * into updated_project;

  insert into public.project_activity(project_id, actor_id, action, details)
  values (
    project_uuid,
    auth.uid(),
    'project_status_changed',
    jsonb_build_object('status', next_status)
  );

  return updated_project;
end;
$$;

grant execute on function public.save_project_revision(
  uuid,
  text,
  text,
  jsonb,
  integer
) to authenticated;
grant execute on function public.record_drive_package_sync(
  uuid,
  text,
  text,
  bigint
) to authenticated;
grant execute on function public.set_project_status(uuid, text)
  to authenticated;

revoke execute on function public.save_project_revision(
  uuid,
  text,
  text,
  jsonb,
  integer
) from public, anon;
revoke execute on function public.record_drive_package_sync(
  uuid,
  text,
  text,
  bigint
) from public, anon;
revoke execute on function public.set_project_status(uuid, text)
  from public, anon;

revoke execute on function public.prepare_project_work_item()
  from public, anon, authenticated;
revoke execute on function public.prepare_project_approval()
  from public, anon, authenticated;
revoke execute on function public.log_project_intelligence_activity()
  from public, anon, authenticated;

commit;
